Audits:
    Games Played:
        value: 0
        order: 0
        key: "games_played"
    Games Started: 0
        value: 0
        order: 1
        key: "games_played"
    Avg Game Time:
        value: "0:00"
        order: 2
        key: "average_game_time"
    Balls Played:
        value: 0
        order: 2
        key: "balls_played"
    Avg Ball Time:
        value: "0:00"
        order: 3
        key: "average_ball_time"
    Avg Score:
        value: 0
        order: 4
        key: "average_score"
    Avg Extra Balls:
        value: 0
        order: 4
        key: "average_extra_balls"
