coin.free_play: "NO"
coin.pricing: "1 FOR 0.25"
coin.max_credits: 99
coin.door_type: "0.25 1.00 0.25"
high_score.grand_champion.player: "CLN"
high_score.grand_champion.score: 100000
high_score.place1.player: "JON"
high_score.place1.score: 9000
high_score.place2.player: "DAG"
high_score.place2.score: 8000
high_score.place3.player: "KID"
high_score.place3.score: 7000
high_score.place4.player: "MCG"
high_score.place4.score: 6000
